Yael badillo/create space endpoint
migala-dev/demos-service pull request #10
Opened 2022-10-27 18:20 UTC by YaelBadillo

2022-10-28 15:47 UTC, AlexOrtegaZ requested changes

2022-10-28 15:47 UTC, AlexOrtegaZ commented on src/core/database/services/space.service.ts
> +  public create(newSpace: SpaceDto, userId: string): Promise<Space> {
Los Dtos solo deberían estar en la capa de controlador no en este nivel

2022-10-28 15:47 UTC, AlexOrtegaZ commented on src/modules/spaces/spaces/services/spaces/space.service.ts
> +    const space: Space = await this.spacesService.create(newSpace, userId);
El Dto no debe pasar de la capa de controlador para lograr que este método sea reutilizable

2022-10-28 15:47 UTC, AlexOrtegaZ commented on src/modules/spaces/spaces/services/spaces/space.service.ts
> +  public async create(
Este nombre no es completamente descriptivo por que hace dos cosas:
1. Crear un espacio
2. Crear el primer miembro
Puede llamarse createSpaceAndOwnerMember

2022-10-28 23:55 UTC, YaelBadillo commented on src/core/database/entities/member.entity.ts
> +  public setExpireAt() {
Listo, lo puse con el AfterInsert, que justo ejecuta el método antes de ser insertada la entidad

2022-10-28 23:57 UTC, YaelBadillo commented on src/core/database/entities/space.entity.ts
> +  approvalPercentage: number;
En el sql no tienen default, pero igual el DTO obliga al cliente a mandar unos porcentajes entre 51 a 100 o les manda bad request. Igual si quieres se lo añado.

2022-10-28 23:58 UTC, YaelBadillo commented on src/core/database/services/member.service.ts
> +    invitationStatus: number,
Arreglado

2022-10-28 23:58 UTC, YaelBadillo commented on src/core/database/services/member.service.ts
> +  create(
Añadido

2022-10-28 23:59 UTC, YaelBadillo commented on src/core/database/services/space.service.ts
> +  public create(newSpace: SpaceDto, userId: string): Promise<Space> {
Arreglado, añadí una nueva interfaz como modelo para ello

2022-10-28 23:59 UTC, YaelBadillo commented on src/modules/spaces/spaces/services/spaces/space.service.ts
> +    const space: Space = await this.spacesService.create(newSpace, userId);
Arreglado con el nuevo modelo

2022-10-28 23:59 UTC, YaelBadillo commented on src/modules/spaces/spaces/services/spaces/space.service.ts
> +  public async create(
Listo, ya le cambié el nombre por ese mismo

2022-10-29 00:02 UTC, YaelBadillo commented on src/core/database/entities/space.entity.ts
> +  approvalPercentage: number;
Por cierto, ahí no aparecía el tipo, pero ya lo había añadido

2022-10-29 00:03 UTC, YaelBadillo commented on src/core/database/entities/space.entity.ts
> +  approvalPercentage: number;
Lo puse como @Column({ type: 'integer' })

2022-11-07 20:48 UTC, AlexOrtegaZ requested changes

2022-11-07 20:48 UTC, AlexOrtegaZ commented on src/modules/spaces/spaces/space.controller.ts
> +    const newSpace: SpaceModel = { ...spaceDto };
Esto es un hack, solo en mascaras el tipo, mejor envía los datos por separado, elimina el SpaceModel

2022-11-08 05:04 UTC, YaelBadillo commented on src/modules/spaces/spaces/space.controller.ts
> +    const newSpace: SpaceModel = { ...spaceDto };
Listo, space model removido

2022-11-09 05:14 UTC, AlexOrtegaZ approved these changes

2022-11-09 05:14 UTC, merged