Yael badillo/send invitations endpoint
migala-dev/demos-service pull request #12
Opened 2022-11-05 01:58 UTC by YaelBadillo

2022-11-07 21:28 UTC, AlexOrtegaZ requested changes

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +      return memberCreated;
Esta función hace dos cosas hay que separar, que pasa en el caso de que el userId llegue nulo?
Esta función ni siquiera debería de llamarse

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +      const memberCreated = await this.membersService.create(
Esto deberías ponerlo en otra función,
deberas tener una función para crear un nuevo member

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +      const memberCreated = await this.membersService.create(
createNewMemeber

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +      } as User);
Aqui no deberias convertirlo a User ya te debería llegar ese tipo

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +  private async getUserId(phoneNumber: string): Promise<string> {
Esta función hace dos cosas: 
getUserId
createUser
Separala en dos y trabaja sobre la función de arriba

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +    usersToInvite: UserToInviteModel[],
UserToInvateModel no me parece buen nombre, cámbialo por Invitation

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/services/member.service.ts
> +    usersToInvite: UserToInviteModel[],
En general evita ponerle a algo Model en el nombre (a menos que este justificado)

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/member.controller.ts
> +    const usersToInvite: UserToInviteModel[] = users.map(
Cambia UserToInviteModel por Invitation
Y manéjalo como una propiedad dentro del DTO

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/core/guards/space-member/space-member.guard.spec.ts
> +    it('should return true if the request is validated', async () => {
Supongo que aqui te referías si el usuario es miembro del espacio?

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/core/guards/space-member/space-member.guard.ts
> +    request.member = await this.getMemberAndValidate(user.userId, spaceId);
Mejor que los errores estén directos en esta función y así evitamos poner el "AndValidate"

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/core/guards/space-member/space-member.guard.ts
> +    request.space = await this.getSpaceAndValidate(spaceId);
No es posible concatenar los guards internamente para que no vuelvas a hacer esta llamada independiente a la otra?

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/core/guards/space-member/space-member.guard.ts
> +export class SpaceMemberGuard implements CanActivate {
Cambiemos este nombre por uno mas descritivo como "IsUserASpaceMemeberGuard"

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/member.controller.ts
> +    const usersToInvite: UserToInviteModel[] = users.map(
Evita hacer este tipo de conversaciones que solo castean tipos, en este caso puedes recibir el DTO parece mas conveniente que hacer este tipo de casteos

2022-11-07 21:28 UTC, AlexOrtegaZ commented on src/modules/spaces/members/member.controller.ts
> +    @Req() { space, member }: SpaceAndMemberRequest,
Aqui Recuerda seguir el mismo patron que llevamos:

    @SpaceFromRequest() space: Space,
    @MemberFromRequest() member: Member,

2022-11-08 20:07 UTC, YaelBadillo commented on src/core/guards/space-member/space-member.guard.ts
> +    request.space = await this.getSpaceAndValidate(spaceId);
Aquí te refieres a concatenar el SpaceMember guard con el SpaceRoles guard?

2022-11-08 20:46 UTC, YaelBadillo commented on src/core/database/services/user.service.ts
> +  public saveUser({ ...user }: User): Promise<User> {
No hay ninguna razón, ya lo corregí para que reciba la instancia directamente

2022-11-09 05:19 UTC, AlexOrtegaZ approved these changes

2022-11-09 05:19 UTC, merged