Yael badillo/register user device endpoint
migala-dev/demos-service pull request #5
Opened 2022-10-03 03:58 UTC by YaelBadillo

2022-10-08 07:21 UTC, AlexOrtegaZ requested changes

2022-10-08 07:21 UTC, AlexOrtegaZ commented on src/modules/auth/controllers/auth/services/auth/auth.service.spec.ts
> +    it('should return an instance of UserDevice with the same properties passed to the mathod', async () => {
"mathod" a "method"

2022-10-08 07:37 UTC, AlexOrtegaZ requested changes

2022-10-08 07:37 UTC, AlexOrtegaZ commented on src/core/database/entities/user-device.entity.ts
> +  updatedAt: string;
Estos hay que cambiarlos de la siguiente forma: 
  @Column({ type: 'timestamptz' })
  createdAt: Date;

  @Column({ type: 'timestamptz' })
  updatedAt: Date;

2022-10-08 07:37 UTC, AlexOrtegaZ commented on src/core/database/entities/user-device.entity.ts
> +  deviceId: string;
Tanto el deviceId como el userId no pueden ser nulos

2022-10-10 17:25 UTC, YaelBadillo commented on src/modules/auth/controllers/auth/services/auth/auth.service.spec.ts
> +    it('should return an instance of UserDevice with the same properties passed to the mathod', async () => {
Corregido

2022-10-10 17:26 UTC, YaelBadillo commented on src/core/database/entities/user-device.entity.ts
> +  updatedAt: string;
Cambiados

2022-10-10 17:26 UTC, YaelBadillo commented on src/core/database/entities/user-device.entity.ts
> +  deviceId: string;
Corregidos

2022-10-11 00:29 UTC, AlexOrtegaZ approved these changes

2022-10-11 00:29 UTC, merged