Yael badillo/update profile picture endpoint
migala-dev/demos-service pull request #8
Opened 2022-10-24 04:10 UTC by YaelBadillo

2022-10-24 19:14 UTC, AlexOrtegaZ requested changes

2022-10-24 19:14 UTC, AlexOrtegaZ commented on src/modules/auth/guards/jwt-auth.guard.ts
> +    return super.canActivate(context);
Aqui puedes cambiar esto por:
 return isPublic || super.canActivate(context);

2022-10-24 19:14 UTC, AlexOrtegaZ commented on src/modules/auth/controllers/user/services/file/file.service.ts
> +    this.s3 = new S3();
Hay algún motivo para hacer la asignación en el constructor y no en la declaración de la linea 8?

2022-10-24 19:14 UTC, AlexOrtegaZ commented on src/modules/auth/controllers/user/services/file/file.service.ts
> +  public deletePublicFile(imageKey: string): void {
Recuerda siempre tener el mismo nombre para el mismo concepto en todos los lugares de la App, si le pones imageKey, tambien en la linea 20 debería llamarse imageKey, y la función gernerateKey debería de llamarse generateImageKey

2022-10-24 19:14 UTC, AlexOrtegaZ commented on src/core/decorators/auth/user-from-request/user-from-request.decorator.ts
> +    return data ? user?.[data] : user;
data no es un nombre descriptivo

2022-10-24 21:24 UTC, YaelBadillo commented on jwks.json
> +  "keys": [{
Actualizado

2022-10-24 21:25 UTC, YaelBadillo commented on src/modules/auth/guards/jwt-auth.guard.ts
> +    return super.canActivate(context);
Cambiado

2022-10-24 21:25 UTC, YaelBadillo commented on src/modules/auth/controllers/user/services/file/file.service.ts
> +    this.s3 = new S3();
Ninguno, ya lo cambié

2022-10-24 21:25 UTC, YaelBadillo commented on src/modules/auth/controllers/user/services/file/file.service.ts
> +  public deletePublicFile(imageKey: string): void {
Corregido

2022-10-24 21:25 UTC, YaelBadillo commented on src/core/decorators/auth/user-from-request/user-from-request.decorator.ts
> +    return data ? user?.[data] : user;
Cambiado por propertyName

2022-10-24 21:26 UTC, YaelBadillo commented on src/core/decorators/auth/user-from-request/user-from-request.decorator.ts
> +  (data: string, ctx: ExecutionContext): User | string | Date => {
Cambiado a context

2022-10-30 14:40 UTC, AlexOrtegaZ requested changes

2022-10-30 14:40 UTC, AlexOrtegaZ commented on src/modules/auth/guards/jwt-auth.guard.spec.ts
> +      expect(reflectorSpy.getAllAndOverride).toHaveBeenCalledTimes(1);
Aqui en esta prueba revisas si el método se llamo, pero lo que deberías de probar es por que se llamo, por lo que esta prueba se me hace demas.

2022-10-30 14:40 UTC, AlexOrtegaZ commented on src/modules/auth/guards/jwt-auth.guard.spec.ts
> +      expect(result).toBeTruthy();
Hay que probar el caso en el que sea falso

2022-10-30 20:24 UTC, YaelBadillo commented on src/modules/auth/guards/jwt-auth.guard.spec.ts
> +      expect(reflectorSpy.getAllAndOverride).toHaveBeenCalledTimes(1);
Prueba removida

2022-10-30 20:25 UTC, YaelBadillo commented on src/modules/auth/guards/jwt-auth.guard.spec.ts
> +      expect(result).toBeTruthy();
Prueba hecha

2022-11-07 20:41 UTC, AlexOrtegaZ approved these changes

2022-11-07 20:41 UTC, merged